version: '3.9'

services:
  vinconomy_server:
    container_name: vinconomy_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "<external_server_port>:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://vinconomy_db:3306/server_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: <uname_here>
      SPRING_DATASOURCE_PASSWORD: <pwd_here>
      # Optional: customize JVM or Spring profiles
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    depends_on:
      - vinconomy_db
    restart: always

  vinconomy_db:
    extends:
      file: ./mysql/docker-compose.db.yml
      service: vinconomy_db

volumes:
  mysql_data: