version: '3.9'

services:
  vinconomy_db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vinconomy_db
    restart: always
    ports:
      - "<external_db_port>:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: